import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatCurrency, formatDate } from './format';

/**
 * Generic CSV export. Triggers a browser download.
 * @param {string} filename - e.g. "expenses.csv"
 * @param {string[]} headers
 * @param {Array<Array<string|number>>} rows
 */
export function exportToCSV(filename, headers, rows) {
  const escapeCell = (cell) => {
    const val = String(cell ?? '');
    if (val.includes(',') || val.includes('"') || val.includes('\n')) {
      return '"' + val.replace(/"/g, '""') + '"';
    }
    return val;
  };

  const csvRows = [
    headers.map(escapeCell).join(','),
    ...rows.map((row) => row.map(escapeCell).join(',')),
  ];

  const csvContent = '\uFEFF' + csvRows.join('\r\n'); // BOM for Excel UTF-8 compatibility
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, filename);
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function addBrandedHeader(doc, title, subtitle) {
  doc.setFillColor(11, 31, 59); // navy
  doc.rect(0, 0, 210, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('BuildTrack', 14, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Construction Expense Tracker', 14, 19);

  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }), 196, 13, { align: 'right' });

  doc.setTextColor(20, 20, 20);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(title, 14, 38);
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, 14, 44);
  }
  doc.setTextColor(20, 20, 20);
  return subtitle ? 50 : 44;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by BuildTrack — Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }
}

/** Export the Expenses table for a site as a PDF. */
export function exportExpensesPDF(site, expenses) {
  const doc = new jsPDF();
  let y = addBrandedHeader(doc, 'Expense Report', site?.name ? `Site: ${site.name}` : undefined);

  const total = expenses.reduce((s, e) => s + Number(e.amount), 0);

  autoTable(doc, {
    startY: y + 4,
    head: [['Expense Name', 'Category', 'Date', 'Amount']],
    body: expenses.map((e) => [e.name, e.category, formatDate(e.date), formatCurrency(e.amount)]),
    headStyles: { fillColor: [11, 31, 59] },
    styles: { fontSize: 9 },
    foot: [['', '', 'Total', formatCurrency(total)]],
    footStyles: { fillColor: [245, 245, 245], textColor: [20, 20, 20], fontStyle: 'bold' },
  });

  addFooter(doc);
  doc.save(`${(site?.name || 'site').replace(/\s+/g, '-')}-expenses.pdf`);
}

/** Export the Worker/Labor table for a site as a PDF. */
export function exportLaborPDF(site, workers, getWorkerDaysPresent, totalLaborCost) {
  const doc = new jsPDF();
  let y = addBrandedHeader(doc, 'Labor Cost Report', site?.name ? `Site: ${site.name}` : undefined);

  autoTable(doc, {
    startY: y + 4,
    head: [['Worker', 'Role', 'Daily Wage', 'Days Present', 'Total Cost']],
    body: workers.map((w) => {
      const days = getWorkerDaysPresent(w.id);
      return [w.name, w.role, formatCurrency(w.dailyWage), String(days), formatCurrency(days * w.dailyWage)];
    }),
    headStyles: { fillColor: [11, 31, 59] },
    styles: { fontSize: 9 },
    foot: [['', '', '', 'Total', formatCurrency(totalLaborCost)]],
    footStyles: { fillColor: [245, 245, 245], textColor: [20, 20, 20], fontStyle: 'bold' },
  });

  addFooter(doc);
  doc.save(`${(site?.name || 'site').replace(/\s+/g, '-')}-labor.pdf`);
}

/** Export the full Budget vs Actual report as a PDF. */
export function exportBudgetReportPDF({ site, materialCost, laborCost, totalActual, difference, isOver, categoryBreakdown }) {
  const doc = new jsPDF();
  let y = addBrandedHeader(doc, 'Budget vs Actual Report', `Site: ${site.name}${site.location ? ' • ' + site.location : ''}`);

  // Status banner
  doc.setFillColor(...(isOver ? [254, 226, 226] : [220, 252, 231]));
  doc.roundedRect(14, y + 2, 182, 16, 2, 2, 'F');
  doc.setTextColor(...(isOver ? [185, 28, 28] : [22, 101, 52]));
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(isOver ? 'OVER BUDGET' : 'WITHIN BUDGET', 18, y + 9);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const msg = isOver
    ? `Spending has exceeded the planned budget by ${formatCurrency(Math.abs(difference))}.`
    : `${formatCurrency(difference)} remaining out of the total planned budget.`;
  doc.text(msg, 18, y + 14.5);
  doc.setTextColor(20, 20, 20);

  y += 24;

  autoTable(doc, {
    startY: y,
    head: [['Summary', 'Amount']],
    body: [
      ['Planned Budget', formatCurrency(site.budget)],
      ['Actual Spending', formatCurrency(totalActual)],
      ['Material + Misc Costs', formatCurrency(materialCost)],
      ['Labor Costs', formatCurrency(laborCost)],
      [isOver ? 'Over Budget By' : 'Under Budget By', formatCurrency(Math.abs(difference))],
    ],
    headStyles: { fillColor: [11, 31, 59] },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
    tableWidth: 182,
  });

  const afterSummaryY = doc.lastAutoTable.finalY + 10;

  autoTable(doc, {
    startY: afterSummaryY,
    head: [['Category', 'Amount', '% of Actual Spend']],
    body: categoryBreakdown
      .slice()
      .sort((a, b) => b.value - a.value)
      .map((c) => [c.name, formatCurrency(c.value), `${((c.value / totalActual) * 100 || 0).toFixed(1)}%`]),
    headStyles: { fillColor: [255, 140, 0] },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
    tableWidth: 182,
  });

  addFooter(doc);
  doc.save(`${site.name.replace(/\s+/g, '-')}-budget-report.pdf`);
}

/** Export Budget vs Actual category breakdown as CSV. */
export function exportBudgetReportCSV(site, { materialCost, laborCost, totalActual, difference, isOver, categoryBreakdown }) {
  const headers = ['Metric', 'Value'];
  const rows = [
    ['Site', site.name],
    ['Planned Budget', site.budget],
    ['Actual Spending', totalActual],
    ['Material + Misc Costs', materialCost],
    ['Labor Costs', laborCost],
    [isOver ? 'Over Budget By' : 'Under Budget By', Math.abs(difference)],
    [],
    ['Category', 'Amount'],
    ...categoryBreakdown.map((c) => [c.name, c.value]),
  ];
  exportToCSV(`${site.name.replace(/\s+/g, '-')}-budget-report.csv`, headers, rows);
}
